### ISSUE TITLE
Change Note Type Name 

### ISSUE THREAD

**Issue by Jiingstudii** [kelciour/improved-quizlet-to-anki-21-importer#10]
Hello, so usually after importing the deck from quizlet to anki, the note type will be called Basic Quizlet. Lately I changed some settings to this note type and to make it more clear what I did I renamed the Note Type. Now I imported again from quizlet and it made a new Note Type again called Basic Quizlet. Is there any possibilities to select to what note type you want the imported decks to go to?

**Comment by kelciour** [comment]
This will be a nice feature, but the add-on is unlikely to be updated in the future if it works. A few possible options:

1. Go to Tools > Add-ons > Improved Quizlet ... > View Files, edit `__init__.py` in any text editor and replace all appearances of "Basic Quizlet" with a new note type, restart Anki.

    https://github.com/kelciour/improved-quizlet-to-anki-21-importer/blob/master/__init__.py#L126-L134

2. After using the add-on to import Quizlet sets, go to the card browser and use Change Note Type.

**Comment by Jiingstudii** [comment]
Oh alright! Thank you!!!
