### ISSUE TITLE
Need help importing private Quizlet decks.

### ISSUE THREAD

**Issue by julian1887** [kelciour/improved-quizlet-to-anki-21-importer#4]
I`ve tried to import a private Quizlet deck, following the description on the add-on page with cookies. Unfortunately i cant do it and i dont even know what my issue is. Maybe you could explain it another time for a noob?

**Comment by kelciour** [comment]
Reset your config file to remove cookies and try with qlts.

![image](https://user-images.githubusercontent.com/16260735/98676918-51759580-236d-11eb-8b7f-5421b09a8a04.png)

**Comment by julian1887** [comment]
Theres no qlts there. Maybe because the page is german?

**Comment by kelciour** [comment]
If you have a Quizlet account and logged in, "qlts" should be there and I'm not sure why it's not there. Maybe Quizlet changed something on their end. Maybe try again with "cookies", i.e. open the Quizlet set in your web browser, then open DevTools (F12), switch to the Network tab, refresh the page (F5) and copy cookies from the request to "flash-cards/".

![image](https://user-images.githubusercontent.com/16260735/98713045-25233e80-2398-11eb-9f75-6eaf0d52c346.png)

Do you have access to the private Quizlet set? The add-on can only import your own private Quizlet sets.

**Comment by julian1887** [comment]
Alright, thank you
