### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by delaneydo** [kelciour/improved-quizlet-to-anki-21-importer#5]
Hello! I seem to be having a similar problem as a few other people, every time I try to import my quizlets it says it is behind a captcha. I have tried uninstalling the addon and readding it, as well as deleting the app and redownloading it. I have also tried the Ctrl+G option but just keep getting captchas to solve without unlocking the deck. I have attached the files below that I am trying to import:

https://quizlet.com/555684334/pulmonology-flash-cards/
https://quizlet.com/552558671/cardiology-flash-cards/
https://quizlet.com/554509122/orthopedicsrheumatology-flash-cards/
https://quizlet.com/555051805/gastroenterology-flash-cards/
https://quizlet.com/556271982/heent-flash-cards/
https://quizlet.com/555953033/neurology-flash-cards/

any help would be greatly appreciated!!

**Comment by kelciour** [comment]
That's strange that Ctrl+G doesn't work after installing https://github.com/kelciour/improved-quizlet-to-anki-21-importer/releases/tag/v1.0.0-captcha

Once the captcha is solved, the Quizlet set should be unblocked and visible and the add-on should be able to import it.

Theoretically, a new VPN connection to change the IP address might help to bypass the issue, or maybe not.

The add-on works fine for me, I can't reproduce it and I'm not sure what else I can do. Someone, who can reproduce it, can install Burp Suite or something similar to compare requests from the add-on and the web browser in the incognito mode and find a difference.

I uploaded imported Quizlet decks here - https://send.vis.ee/download/295490a27d03589e/#7s4K6pya6QLrvTX2jqgR_g
